name: Deploy to GKE

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GKE_PROJECT: itis-441214
      GKE_CLUSTER: itiitiss
      GKE_ZONE: europe-west12-a

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
          project_id: ${{ env.GKE_PROJECT }} 

      - name: GKE Credentials
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
      
      - name: Deploy the Docker image to the GKE cluster
        run: kubectl apply -f k8s/ 

      

